add firebase_functions suite

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -93,3 +93,42 @@ jobs:
           else
             echo "app_flask=false" >> $GITHUB_STATE
           fi
+
+      - name: Run all suites if no tags found
+        if: steps.set_client_react.outputs.client_react == 'false' && steps.set_firebase_functions.outputs.firebase_functions == 'false' && steps.set_app_flask.outputs.app_flask == 'false'
+        run: |
+          # Run all three suites
+          echo "all_test_suite=true" >> $GITHUB_STATE
+
+  run-firebase_functions-suite:
+    runs-on: ubuntu-latest
+    needs: check-remaining-tags
+    if: needs.check-remaining-tags.outputs.all_test_suite == 'true' || needs.check-remaining-tags.outputs.firebase_functions == 'true'
+    defaults:
+      run:
+        working-directory: database/firebase/functions    
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.x
+
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt  # Install dependencies
+
+      - name: Run tests
+        run: |
+          python -m unittest discover -s tests  # Run test on the functions/tests directory
+
+      - name: Check test status and prevent merge/push on failure
+        if: ${{ failure() }}
+        run: exit 1  # Exit with a non-zero code to fail the workflow          
+
+
+
+
+
