test [firebase_functions] only

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -29,10 +29,29 @@ jobs:
     runs-on: ubuntu-latest
     needs: check-tags-and-run
     if: ${{ needs.check-tags-and-run.outputs.run_firebase_functions == 'true' || needs.check-tags-and-run.outputs.run_all_suites == 'true' }}
+    defaults:
+      run:
+        working-directory: database/firebase/functions
     steps:
-      - name: run suite
-        run: echo "run_firebase_functions-suite"     
-      # Steps to run firebase_functions tests...
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.x
+
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt  # Install dependencies
+
+      - name: Run tests
+        run: |
+          python -m unittest discover -s tests  # Run test on the functions/tests directory
+
+      - name: Check test status and prevent merge/push on failure
+        if: ${{ failure() }}
+        run: exit 1  # Exit with a non-zero code to fail the workflow
 
   run-app_flask-suite:
     runs-on: ubuntu-latest
@@ -83,7 +102,8 @@ jobs:
           else
             echo "::set-output name=app_flask::false"
           fi
-          
+
+
       - name: Set all_suites output
         id: set_all_suites
         run: |
